FROM python:3.10.12-slim-bullseye

COPY . /app

WORKDIR /app
#-> cd /app/

RUN python3 -m venv /opt/venv
# create venv in /opt/venv

RUN /opt/venv/bin/pip install pip--upgrade pip && \
    /opt/venv/bin/pip install -r requirements.txt && \
    chmod +x entrypoint.sh
# exec pip from /opt/venv

CMD ["/app/entrypoint.sh"]
